/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scenes/Index.ls
 */
export class MapUiBase extends Laya.Scene {
    public bg: Laya.Panel;
}

